### ISSUE TITLE
Erstellen von Modulen funktioniert nicht mehr

### ISSUE THREAD

**Issue by lwsm99** [THM-ATLAS/spring-backend#170]
ERROR: duplicate key value violates unique constraint "module_pkey"
Detail: Key (module_id)=(1) already exists.

at com.example.atlasbackend.service.ModuleService.createModule(ModuleService.kt:50) ~[main/:na]
at com.example.atlasbackend.controller.ModuleController.postModule(ModuleController.kt:67) ~[main/:na]

**Comment by lwsm99** [comment]
Dasselbe Problem auch bei User, Exercises etc. 
IDs werden von 1 an wieder inkrementiert, statt höchstexistierende ID
